Move clean-up to the bottom of base/Dockerfile (#1726)
Without this change ./build.sh errors out late in the game with the error below, presumably because a new transitive dependency requires compilation but the clean-up stanza has already removed gcc.

```
  Running setup.py install for setproctitle: started
    Running setup.py install for setproctitle: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E4jhlY/setproctitle/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dXyR7P-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'setproctitle' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_SYS_PRCTL_H=1 -DSPT_VERSION=1.1.10 -I/usr/include/python2.7 -c src/setproctitle.c -o build/temp.linux-x86_64-2.7/src/setproctitle.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E4jhlY/setproctitle/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dXyR7P-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-E4jhlY/setproctitle/
The command '/bin/sh -c cd /datalab/lib/pydatalab &&     pip install --upgrade-strategy only-if-needed --no-cache-dir . &&     pip install --upgrade-strategy only-if-needed /datalab/lib/pydatalab/solutionbox/image_classification/. &&     pip install --upgrade-strategy only-if-needed /datalab/lib/pydatalab/solutionbox/structured_data/. &&     pip3 install --upgrade-strategy only-if-needed --no-cache-dir . &&     pip3 install --upgrade-strategy only-if-needed /datalab/lib/pydatalab/solutionbox/image_classification/. &&     pip3 install --upgrade-strategy only-if-needed /datalab/lib/pydatalab/solutionbox/structured_data/. &&     jupyter nbextension install --py datalab.notebook &&     jupyter nbextension install --py google.datalab.notebook &&     jupyter nbextension enable --py widgetsnbextension &&     rm datalab/notebook/static/*.js google/datalab/notebook/static/*.js &&     mkdir -p /datalab/nbconvert &&     cp -R /usr/local/share/jupyter/nbextensions/gcpdatalab/* /datalab/nbconvert &&     ln -s /usr/local/lib/python2.7/dist-packages/notebook/static/custom/custom.css /datalab/nbconvert/custom.css &&     cd /' returned a non-zero code: 1
```